//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pruebas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activos
    {
        public string NoControlInv { get; set; }
        public string Descripcion { get; set; }
        public decimal ImporteIVA { get; set; }
        public string Cambios { get; set; }
        public string Monitoreo { get; set; }
        public string RFC { get; set; }
    }
}
