//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pruebas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activos
    {
        public string NoControlInv { get; set; }
        public string Descripcion { get; set; }
        public decimal ImporteIVA { get; set; }
        public string Cambios { get; set; }
        public string Monitoreo { get; set; }
        public string RFC { get; set; }
    }
}
