//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pruebas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permiso
    {
        public int IdPermiso { get; set; }
        public int RolUsuId { get; set; }
        public int OpcionId { get; set; }
        public bool Permitido { get; set; }
    
        public virtual Opcion Opcion { get; set; }
        public virtual RolUsuario RolUsuario { get; set; }
    }
}
